create table Dyqani
(
  id integer primary key,
  name varchar(45),
  adresa varchar(45),
  city varchar(45)
);

INSERT INTO Dyqani (id, name, adresa, city) VALUES
(1, 'Dyqani Alfa', 'Rruga e Dajti 12', 'Tiranë'),
(2, 'Dyqani Beta', 'Rruga e Elbasanit 5', 'Shkodër'),
(3, 'Dyqani Gamma', 'Rruga e Vlorës 9', 'Fier'),
(4, 'Dyqani Delta', 'Rruga Shkupi 4', 'Përmet'),
(5, 'Dyqani Epsilon', 'Rruga e Bogas 13', 'Gjirokastër'),
(6, 'Dyqani Zeta', 'Rruga 5 Maj 7', 'Sarandë'),
(7, 'Dyqani Eta', 'Rruga e Dajti 3', 'Kukës'),
(8, 'Dyqani Theta', 'Rruga e Shijakut 10', 'Vlorë'),
(9, 'Dyqani Iota', 'Rruga e Tiranës 8', 'Lezhë'),
(10, 'Dyqani Kappa', 'Rruga e Durresit 2', 'Korçë'),
(11, 'Dyqani Lambda', 'Rruga e Gjirokastrës 4', 'Përmet'),
(12, 'Dyqani Mu', 'Rruga e Ballshit 14', 'Fier'),
(13, 'Dyqani Nu', 'Rruga Kavajës 3', 'Elbasan'),
(14, 'Dyqani Xi', 'Rruga Hoxhaj 6', 'Shkodër'),
(15, 'Dyqani Omicron', 'Rruga e Rrëshenit 11', 'Durrës'),
(16, 'Dyqani Pi', 'Rruga Gjirokastra 2', 'Shijak'),
(17, 'Dyqani Rho', 'Rruga Besëlidhja 8', 'Tiranë'),
(18, 'Dyqani Sigma', 'Rruga 29 Nëntori 3', 'Korçë'),
(19, 'Dyqani Tau', 'Rruga e Tren 12', 'Sarandë'),
(20, 'Dyqani Upsilon', 'Rruga e Shkumbinit 4', 'Kukës'),
(21, 'Dyqani Phi', 'Rruga e Fierit 9', 'Vlorë'),
(22, 'Dyqani Chi', 'Rruga e Mbretneshës 7', 'Përmet'),
(23, 'Dyqani Psi', 'Rruga e Elbasanit 6', 'Shkodër'),
(24, 'Dyqani Omega', 'Rruga Bregdeti 11', 'Fier'),
(25, 'Dyqani Alpha 2', 'Rruga Vlora 8', 'Tiranë'),
(26, 'Dyqani Beta 2', 'Rruga Durresit 15', 'Shijak'),
(27, 'Dyqani Gamma 2', 'Rruga Elbasani 1', 'Korçë'),
(28, 'Dyqani Delta 2', 'Rruga Lushnjës 5', 'Vlorë'),
(29, 'Dyqani Epsilon 2', 'Rruga Shkumbini 6', 'Sarandë'),
(30, 'Dyqani Zeta 2', 'Rruga 1 Maj 4', 'Lezhë'),
(31, 'Dyqani Eta 2', 'Rruga Kukësit 9', 'Shkodër'),
(32, 'Dyqani Theta 2', 'Rruga Pejës 7', 'Tiranë'),
(33, 'Dyqani Iota 2', 'Rruga Stacionit 2', 'Fier'),
(34, 'Dyqani Kappa 2', 'Rruga Shkupi 3', 'Elbasan'),
(35, 'Dyqani Lambda 2', 'Rruga Barrikadave 5', 'Gjirokastër'),
(36, 'Dyqani Mu 2', 'Rruga Kombinat 8', 'Tiranë'),
(37, 'Dyqani Nu 2', 'Rruga Sheshi 6', 'Përmet'),
(38, 'Dyqani Xi 2', 'Rruga Vlorës 12', 'Durrës'),
(39, 'Dyqani Omicron 2', 'Rruga Shtator 9', 'Vlorë'),
(40, 'Dyqani Pi 2', 'Rruga Selitë 4', 'Sarandë'),
(41, 'Dyqani Rho 2', 'Rruga Blloku 10', 'Korçë'),
(42, 'Dyqani Sigma 2', 'Rruga Plazhi 15', 'Elbasan'),
(43, 'Dyqani Tau 2', 'Rruga Krasniqi 5', 'Shkodër'),
(44, 'Dyqani Upsilon 2', 'Rruga Shkumbin 6', 'Tiranë'),
(45, 'Dyqani Phi 2', 'Rruga Tiranë 1', 'Përmet'),
(46, 'Dyqani Chi 2', 'Rruga Xhenxhi 3', 'Fier'),
(47, 'Dyqani Psi 2', 'Rruga Barç 2', 'Durrës'),
(48, 'Dyqani Omega 2', 'Rruga Rrëza 4', 'Korçë'),
(49, 'Dyqani Alpha 3', 'Rruga Piskovë 5', 'Tiranë'),
(50, 'Dyqani Beta 3', 'Rruga Rrëshen 3', 'Shkodër'),
(51, 'Dyqani Gamma 3', 'Rruga Kuvendi 8', 'Përmet'),
(52, 'Dyqani Delta 3', 'Rruga Sheshi i Ri 6', 'Fier'),
(53, 'Dyqani Epsilon 3', 'Rruga Ilda 3', 'Elbasan'),
(54, 'Dyqani Zeta 3', 'Rruga Albania 4', 'Shijak'),
(55, 'Dyqani Eta 3', 'Rruga Trin 2', 'Korçë'),
(56, 'Dyqani Theta 3', 'Rruga Durësi 8', 'Sarandë'),
(57, 'Dyqani Iota 3', 'Rruga Bjeshkët 10', 'Shkodër'),
(58, 'Dyqani Kappa 3', 'Rruga Zogaj 6', 'Tiranë'),
(59, 'Dyqani Lambda 3', 'Rruga Martyrs 11', 'Fier'),
(60, 'Dyqani Mu 3', 'Rruga Bashkimi 7', 'Vlorë'),
(61, 'Dyqani Nu 3', 'Rruga Ajsha 6', 'Sarandë'),
(62, 'Dyqani Xi 3', 'Rruga Nishani 8', 'Korçë'),
(63, 'Dyqani Omicron 3', 'Rruga Kamëz 10', 'Shkodër'),
(64, 'Dyqani Pi 3', 'Rruga Treni 4', 'Përmet'),
(65, 'Dyqani Rho 3', 'Rruga Kërkush 7', 'Tiranë'),
(66, 'Dyqani Sigma 3', 'Rruga Shitës 12', 'Korçë'),
(67, 'Dyqani Tau 3', 'Rruga Pejë 15', 'Vlorë'),
(68, 'Dyqani Upsilon 3', 'Rruga Kavaja 13', 'Shkodër'),
(69, 'Dyqani Phi 3', 'Rruga Bajkaj 4', 'Sarandë'),
(70, 'Dyqani Chi 3', 'Rruga Pashë 6', 'Tiranë'),
(71, 'Dyqani Psi 3', 'Rruga Dimër 8', 'Shijak'),
(72, 'Dyqani Omega 3', 'Rruga e Dukagjin 10', 'Elbasan'),
(73, 'Dyqani Alpha 4', 'Rruga Sheshi i Ri 3', 'Korçë'),
(74, 'Dyqani Beta 4', 'Rruga Bashkimi 7', 'Përmet'),
(75, 'Dyqani Gamma 4', 'Rruga Alea 6', 'Durrës'),
(76, 'Dyqani Delta 4', 'Rruga Dajti 8', 'Fier'),
(77, 'Dyqani Epsilon 4', 'Rruga Gjerbap 9', 'Korçë'),
(78, 'Dyqani Zeta 4', 'Rruga Krenari 10', 'Shkodër'),
(79, 'Dyqani Eta 4', 'Rruga Frashëri 4', 'Vlorë'),
(80, 'Dyqani Theta 4', 'Rruga Mbare 2', 'Sarandë'),
(81, 'Dyqani Iota 4', 'Rruga e Qëndresë 3', 'Përmet'),
(82, 'Dyqani Kappa 4', 'Rruga Jermuk 8', 'Elbasan'),
(83, 'Dyqani Lambda 4', 'Rruga Dukat 7', 'Lezhë'),
(84, 'Dyqani Mu 4', 'Rruga Tërnovë 5', 'Tiranë'),
(85, 'Dyqani Nu 4', 'Rruga Mjedër 9', 'Shkodër'),
(86, 'Dyqani Xi 4', 'Rruga Pallati 4', 'Sarandë'),
(87, 'Dyqani Omicron 4', 'Rruga Fund 10', 'Përmet'),
(88, 'Dyqani Pi 4', 'Rruga Kombinati 2', 'Korçë'),
(89, 'Dyqani Rho 4', 'Rruga Ilir 3', 'Vlorë'),
(90, 'Dyqani Sigma 4', 'Rruga Sheshi 1', 'Fier'),
(91, 'Dyqani Tau 4', 'Rruga Rrëshen 8', 'Durrës'),
(92, 'Dyqani Upsilon 4', 'Rruga Hosh 4', 'Elbasan'),
(93, 'Dyqani Phi 4', 'Rruga Tring 9', 'Tiranë'),
(94, 'Dyqani Chi 4', 'Rruga Qerim 5', 'Lezhë'),
(95, 'Dyqani Psi 4', 'Rruga Kum 3', 'Shkodër'),
(96, 'Dyqani Omega 4', 'Rruga Llambri 2', 'Korçë'),
(97, 'Dyqani Alpha 5', 'Rruga Mamurras 6', 'Tiranë'),
(98, 'Dyqani Beta 5', 'Rruga Krastak 9', 'Përmet'),
(99, 'Dyqani Gamma 5', 'Rruga Kanali 10', 'Elbasan'),
(100, 'Dyqani Delta 5', 'Rruga Vaqarr 12', 'Durrës');


select *
from Dyqani